Web App/api/urls.py
from django.urls import path
from . import views

urlpatterns         = [
    path('update/qr_code/', views.QRCodeCreateAPIView.as_view()),
    path('update/geofencing/', views.GeofencingCreateAPIView.as_view())
]

Web App/battery/urls.py
from django.urls import path
from . import views

app_name            = 'battery'

urlpatterns         = [
    path('', views.BatteryStatus.as_view(), name = 'battery')
]

Web App/block/urls.py
from django.urls import path
from . import views

app_name            = 'block'

urlpatterns         = [
    path('', views.Block.as_view(), name = 'block'),
    path('toggle/', views.Toggle.as_view(), name = 'toggle')
]

Web App/contact/urls.py
from django.urls import path
from . import views

app_name            = 'contact'

urlpatterns         = [
    path('', views.ContactDetails.as_view(), name = 'contact_details'),
    path('delete/<str:id>', views.delete, name = 'delete')
]

Web App/geofencing/urls.py
from django.urls import path
from . import views

app_name        = 'geofencing'

urlpatterns     = [
    path('geofencing/', views.Alert.as_view(), name = 'geofencing')
]

Web App/hackathon_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qr_code_display.urls')),
    path('contact/', include('contact.urls')),
    path('block/', include('block.urls')),
    path('geofencing/', include('geofencing.urls')),
    path('api/', include('api.urls')),
    path('battery/', include('battery.urls'))
]

Web App/qr_code_display/urls.py
from django.urls import path
from . import views

app_name            = 'qr_code_display'

urlpatterns         = [
    path('', views.QRList.as_view(), name = 'qr_list')
]

Web App/api/models.py
from django.shortcuts import render
from django.db import models

# Create your views here.

class QRCodeQuerySet(models.QuerySet):
    pass

class GeofencingQuerySet(models.QuerySet):
    pass

class QRCodeManager(models.Manager):
    def get_queryset(self):
        return QRCodeQuerySet(self.model, using = self._db)

class GeofencingManager(models.Manager):
    def get_queryset(self):
        return GeofencingQuerySet(self.model, using = self._db)

class QRCode(models.Model):
    content         = models.TextField()
    objects         = QRCodeManager()

class Geofencing(models.Model):
    content         = models.TextField()
    objects         = GeofencingManager()

Web App/battery/models.py
from django.db import models

# Create your models here.

Web App/block/models.py
from django.db import models

# Create your models here.

Web App/contact/models.py
from django.db import models

# Create your models here.

Web App/geofencing/models.py
from django.db import models

# Create your models here.

Web App/qr_code_display/models.py
from django.db import models

# Create your models here.

Web App/api/views.py
from rest_framework import mixins, generics
from . import models
from . import serializers as srlz
from django.http import HttpResponse

class QRCodeCreateAPIView(generics.CreateAPIView):
    permission_classes      = []
    authentication_classes  = []
    serializer_class        = srlz.QRCodeSerializer
    queryset                = models.QRCode.objects.all()

    def create(self, serializer):
        print("ok")
        HttpResponse("<script>alert('hello');</script>")
        pass
    # def get(self, request, *args, **kwargs):
    #     HttpResponse("<script>location.reload();</script>")
    #     return self.get(request, *args, **kwargs)

class GeofencingCreateAPIView(generics.RetrieveAPIView):
    permission_classes      = []
    authentication_classes  = []
    serializer_class        = srlz.GeofencingSerializer
    queryset                = models.Geofencing.objects.all()

    def create(self, serializer):
        HttpResponse("<script>location.reload();</script>")
        pass
    # def get(self, request, *args, **kwargs):
    #     HttpResponse("<script>location.reload();</script>")
    #     return self.get(request, *args, **kwargs)

Web App/battery/views.py
from django.shortcuts import render
from django.views.generic import ListView
from hackathon_project.pyrebase_settings import db, auth, user
from django.shortcuts import redirect
from django.urls import reverse

# Create your views here.

class BatteryStatus(ListView):
    template_name           = 'battery/battery.html'

    def get_queryset(self):
        return db.child('battery').get(user['idToken']).val()

Web App/block/views.py
from django.shortcuts import render
from django.views.generic import ListView
from hackathon_project.pyrebase_settings import db, auth, user
from django.shortcuts import redirect
from django.urls import reverse

# Create your views here.

class Block(ListView):
    template_name           = 'block/block.html'

    def get_queryset(self):
        boolVal             = db.child('blockApp').get(user['idToken']).val()

        return boolVal

class Toggle(ListView):
    template_name           = 'block/toggle.html'

    def get(self, request):
        boolVal             = db.child('blockApp').get(user['idToken']).val()

        if boolVal == 0:
            db.child('blockApp').set(1)
        else:
            db.child('blockApp').set(0)

        return redirect(reverse('block:block'))

Web App/contact/views.py
from django.shortcuts import render
from django.views.generic import ListView, DeleteView
from hackathon_project.pyrebase_settings import user, db, auth
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django import forms
from django.contrib import messages

# Create your views here.

class ContactDetails(ListView):
    template_name           = 'contact/contact_details.html'

    def get_queryset(self):
        phoneNumbers    = db.child('phoneNumbers').get(user['idToken'])
        qs              = []

        for phone in phoneNumbers.each():
            dict        = phone.val()
            dict['id']  = phone.key()
            qs.append(dict)
        
        return qs
        
    def post(self, request):
        retVal       = {}

        retVal['name']          = request.POST['name']
        retVal['phone']         = request.POST['phone']

        if retVal['name'] == "":
            messages.error(request, "Name should not be null")
            return redirect(reverse('contact:contact_details'))

        if retVal['phone'] == "":
            messages.error(request, "Phone number should not be null")
            return redirect(reverse('contact:contact_details'))

        try:
            int(retVal['phone'])
            db.child('phoneNumbers').push(retVal)
        except:
            messages.error(request, "Phone number should be integer")

        return redirect(reverse('contact:contact_details'))

def delete(request, **kwargs):
    db.child("phoneNumbers").child(kwargs['id']).remove()

    return redirect(reverse('contact:contact_details'))

Web App/geofencing/views.py
from django.shortcuts import render
from django.views.generic import ListView
from hackathon_project.pyrebase_settings import user, db, auth

# Create your views here.

class Alert(ListView):
    template_name           = 'geofencing/geofencing.html'

    def get_queryset(self):
        return db.child('Location').get(user['idToken']).val()

Web App/qr_code_display/views.py
from django.shortcuts import render
from django.views.generic import ListView
from hackathon_project.pyrebase_settings import user, db, auth

# Create your views here.

class QRList(ListView):
    template_name           = 'qr_code_display/qr_list.html'

    def get_queryset(self):
        return db.child('qrCode').get(user['idToken']).val()

Web App/battery/templates/battery/battery.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-xl">
           <h1 class="text-info text-center">Battery Status</h1>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Device Id</th>
                    <th scope="col">Battery Percentage</th>
                </tr>
            </thead>
            <tbody>
                    {% for key, val in object_list.items %}
                        <tr>
                            <td> {{ key }} </td>
                            <td> {{ val }} </td>
                        </tr>
                    {% endfor %}               
            </tbody>
        </table>
    </div>
{% endblock %}

Web App/block/templates/block/block.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-8">
            {% if object_list == 0 %}
                <h1 class="text-success text-center">Restrictions are Disabled</h1>
            {% else %}
                <h1 class="text-danger text-center">Restrictions are Enabled</h1>
            {% endif %}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-3"></div>
            <div class="col-8">
                <button type="button" class="btn btn-primary btn-lg btn-block"><a href="{% url 'block:toggle' %}" class="text-white">Change Status</a></button>
            </div>
    </div>
{% endblock %}

Web App/block/templates/block/toggle.html
{% extends 'base.html' %}

{% block content %}
    {{ object_list }}
{% endblock %}

Web App/contact/templates/contact/contact_details.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-xl">
           <h1 class="text-info text-center">Emergency Contact Numbers</h1>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone Number</th>
                </tr>
            </thead>
            <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td> {{ item.name }} </td>
                            <td> {{ item.phone }} </td>
                            <td>
                                <button type="submit" class="btn btn-outline-danger btn-sm"><a href="{% url 'contact:delete' id=item.id %}" class="text-danger">Delete</a></button>
                            </td>
                        </tr>
                    {% endfor %}
                    
            </tbody>
        </table>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <input type="text" class="form-control" name="name" placeholder="Name">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" name="phone" placeholder="Phone Number">
                    </div>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags %}
                            <div class="col">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                    <br>
                    <button type="submit" class="btn btn-success btn-lg btn-block">Add Another Phone Number</button>
            </form>
        </div>
    </div>
{% endblock %}

Web App/geofencing/templates/geofencing/geofencing.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-1">
    </div>
    <div class="col-xl">
        <h1 class="text-info text-center">Guest In-Out Details</h1>
        <table class="table table-striped table-hover" id="safe-table">
        	<thead>
				<tr>
					<th scope="col">Device ID</th>
					<th scope="col">Safe Status</th>
				</tr>
        	</thead>
        	<tbody>
				<!-- {% for key, value in object_list.items %}
					<tr>
						<td scope="col">{{ key }}</td>
						<td scope="col">{{ value }}</td>
					</tr>
				{% endfor %} -->
        	</tbody>
        </table>
    </div>
{% endblock %}

Web App/qr_code_display/templates/qr_code_display/qr_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-1">
    </div>
    <div class="col-xl">
        <h1 class="text-info text-center">Guest In-Out Details</h1>
        <table class="table table-striped table-hover" id="ex-table">
        	<thead>
				<tr>
					<th scope="col">Device ID</th>
					<th scope="col">Name</th>
					<th scope="col">Phone Number</th>
					<th scope="col">Email</th>
					<th scope="col">Time</th>
				</tr>
        	</thead>
        	<tbody>
				<!-- {% for key, value in object_list.items %}
					<tr>
						<td scope="col">{{ value.deviceId }}</td>
						<td scope="col">{{ value.name }}</td>
						<td scope="col">{{ value.phone }}</td>
						<td scope="col">{{ value.email }}</td>
						<td scope="col">{{ value.timestamp }}</td>
					</tr>
				{% endfor %} -->
        	</tbody>
        </table>
    </div>
{% endblock %}

Web App/templates/base.html
<!doctype html>
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '.css/main.css' %}">
    <title>HackWithInfy - Home</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-global navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">#HackWithInfy</a>
        </div>
      </div>
    </nav>
    <nav class="navbar-primary" style="margin-top: 5px;">
      <ul class="navbar-primary-menu">
        <li>
          <a href="{% url 'qr_code_display:qr_list' %}" style="border-top:solid 1px white;"><span class="glyphicon glyphicon-list-alt"></span><span class="nav-label">Home</span></a>
          <a href="{% url 'contact:contact_details' %}"><span class="glyphicon glyphicon-list-alt"></span><span class="nav-label">Emergency Contacts</span></a>
          <a id="toggle" href="{% url 'block:block' %}"><span class="glyphicon glyphicon-list-alt"></span><span class="nav-label">Toggle Status</span></a>
          <a href="{% url 'geofencing:geofencing' %}"><span class="glyphicon glyphicon-list-alt"></span><span class="nav-label">Geofencing</span></a>
          <a href="{% url 'battery:battery' %}"><span class="glyphicon glyphicon-list-alt"></span><span class="nav-label">Battery</span></a>
        </li>
      </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://www.gstatic.com/firebasejs/4.1.3/firebase.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
      // Initialize Firebase
      var config = {
        apiKey: "AIzaSyBq9j3Fd9cO6ox6OV9hMKjhPy7_aUpjHqU",
        authDomain: "hackathon-team-13.firebaseapp.com",
        databaseURL: "https://hackathon-team-13.firebaseio.com",
        projectId: "hackathon-team-13",
        storageBucket: "",
        messagingSenderId: "780498370702",
        appId: "1:780498370702:web:b006adf31cceaa69"
      }
        
        firebase.initializeApp(config);
      
       var qrCode = firebase.database().ref('qrCode');
        qrCode.on('value', function(snapshot){
            if(snapshot.exists()){
                var content = '';
                snapshot.forEach(function(data){
                    var val = data.val();
                    content +='<tr>';
                    content += '<td scope="col">' + val.deviceId + '</td>';
                    content += '<td scope="col">' + val.name + '</td>';
                    content += '<td scope="col">' + val.phone + '</td>';
                    content += '<td scope="col">' + val.email + '</td>';
                    content += '<td scope="col">' + val.timestamp + '</td>';
                    content += '</tr>';
                });
                $('#ex-table tbody').html(content);
            }
        });
        
        var Location = firebase.database().ref('Location');
        Location.on('value', function(snapshot){
            if(snapshot.exists()){
                var content = '';
                snapshot.forEach(function(data){
                    var key = data.key;
                    var val = data.val();
                    if(val=='Dangerous')
                    {
                      alert("Your device with ID"+key+"is out of safe zone");
                    }
                    content +='<tr>';
                    content += '<td scope="col">' + key + '</td>';
                    content += '<td scope="col">' + val + '</td>';
                    content += '</tr>';
                });
                $('#safe-table tbody').html(content);
            }
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static '.js/main.js' %}"></script>
  </body>
</html>